name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: Cecosesola
  APK_FILE_NAME: Cecosesola
  STORE_FILE: apps.keystore

jobs:
  build-android-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Set up Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > ${{ env.STORE_FILE }}
        env:
          KEYSTORE_BASE64: ${{ secrets.SIGNING_KEY }}

      - name: Create keystore.properties file
        run: |
          echo "storeFile=${{ env.STORE_FILE }}" > keystore.properties
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Rename APK file
        run: mv app/build/outputs/apk/release/app-release.apk ${{env.APK_FILE_NAME}}.apk

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: ${{env.APK_FILE_NAME}}.apk
          overwrite: true
          if-no-files-found: error
