name: Build Android APK

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: Cecosesola
  APK_FILE_NAME: Cecosesola

jobs:
  build-android-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Generate Keystore
        run: |
          keytool -genkey -v \
            -keystore apps.keystore \
            -alias apps \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass android \
            -keypass android \
            -dname "CN=Apps, OU=Dev, O=Personal, L=City, S=State, C=VE"

      - name: Create keystore.properties
        run: |
          echo "storeFile=apps.keystore" > keystore.properties
          echo "storePassword=android" >> keystore.properties
          echo "keyAlias=apps" >> keystore.properties
          echo "keyPassword=android" >> keystore.properties

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Rename APK file
        run: mv app/build/outputs/apk/release/app-release.apk ${{env.APK_FILE_NAME}}.apk

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: ${{env.APK_FILE_NAME}}.apk
          overwrite: true
          if-no-files-found: error
