name: Build Debug APK

permissions:
  contents: read

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APK_FILE_NAME: Cecosesola-debug

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Rename APK file
        run: mv app/build/outputs/apk/debug/app-debug.apk ${{env.APK_FILE_NAME}}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-build
          path: ${{env.APK_FILE_NAME}}.apk
          overwrite: true
          if-no-files-found: error
